const NAME = 'todos';
const ADD = `${NAME}/ADD`;
const SET_VISIBILITY_FILTER = `${NAME}/SET_VISIBILITY_FILTER`;
const SHOW_ACTIVE = `${NAME}/SHOW_ACTIVE`;
const SHOW_ALL = `${NAME}/SHOW_ALL`;
const SHOW_COMPLETED = `${NAME}/SHOW_COMPLETED`;
const TOGGLE = `${NAME}/TOGGLE`;

export default {
  NAME,
  ADD,
  SET_VISIBILITY_FILTER,
  SHOW_ACTIVE,
  SHOW_ALL,
  SHOW_COMPLETED,
  TOGGLE,
};
